spring.application.name=LocalServiceFinder


spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/Finder2
spring.datasource.username=root
spring.datasource.password=4350

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true




spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yashpanwar4350@gmail.com
spring.mail.password=rlyfdvlbjrwtucei


# --- SMTP Properties ---
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.timeout=5000


# --- Application Specific (Sender Name) ---
app.email.from=yashpanwar4350@gmail.com

mail.smtp.ssl.trust=smtp.gmail.com
# Admin Email (The recipient of the verification requests)
app.admin.email=yashpanwar4350@gmail.com
# Base URL of your backend
app.backend.url=http://localhost:8080
spring.mail.properties.mail.debug=true
logging.level.org.springframework.mail=DEBUG

spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
